baseURL = 'https://example.org/'
languageCode = 'sv_SE'
defaultContentLanguage = "sv"
defaultContentLang = "sv"
title = 'My New Hugo Site'

[params]
    dateFormat = "02 Juni, 2006"


[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menus.main]]
name = 'About'
pageRef = 'about'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
